###########################################################
#             ADUIO & MEL-SPECTRUM                               #
###########################################################
sample_rate: 22050
hop_length: 256
win_length: 1024
n_fft: 1024
n_mels: 80
mel_fmin: 70
mel_fmax: 8000


###########################################################
#             MODEL SETTING                               #
###########################################################
model_name: "LVCNetWaveGAN"
model_params:
    generator_params:
        in_channels: 1        # Number of input channels.
        out_channels: 1       # Number of output channels.
        inner_channels: 8
        cond_channels: 80
        cond_hop_length: 256
        lvc_block_nums: 3
        lvc_layers_each_block: 10
        lvc_kernel_size: 3
        kpnet_hidden_channels: 64
        kpnet_conv_size: 1
        dropout: 0.0
        use_weight_norm: true # Whether to use weight norm.
                            # If set to true, it will be applied to all of the conv layers.

    discriminator_params:
        in_channels: 1        # Number of input channels.
        out_channels: 1       # Number of output channels.
        kernel_size: 3        # Number of output channels.
        layers: 10            # Number of conv layers.
        conv_channels: 64     # Number of chnn layers.
        bias: true            # Whether to use bias parameter in conv.
        use_weight_norm: true # Whether to use weight norm.
                            # If set to true, it will be applied to all of the conv layers.
        nonlinear_activation: "LeakyReLU" # Nonlinear function after each conv.
        nonlinear_activation_params:      # Nonlinear function parameters
            negative_slope: 0.2           # Alpha in LeakyReLU.


###########################################################
#             LOSS SETTING                               #
###########################################################
loss_name: "PWGLoss" 
loss_params:
    stft_loss_params:
        fft_sizes: [1024, 2048, 512]  # List of FFT size for STFT-based loss.
        hop_sizes: [120, 240, 50]     # List of hop size for STFT-based loss
        win_lengths: [600, 1200, 240] # List of window length for STFT-based loss.
        window: "hann_window"         # Window function for STFT-based loss


###########################################################
#             OPTIMIZER & SCHEDULER SETTING               #
###########################################################
opt_name: "PWGOptimizer"
opt_params:
    generator_optimizer_params:
        lr: 0.0001             # Generator's learning rate.
        eps: 1.0e-6            # Generator's epsilon.
        weight_decay: 0.0      # Generator's weight decay coefficient.
    generator_scheduler_params:
        step_size: 200000      # Generator's scheduler step size.
        gamma: 0.5             # Generator's scheduler gamma.
                            # At each step size, lr will be multiplied by this parameter.
    discriminator_optimizer_params:
        lr: 0.00005            # Discriminator's learning rate.
        eps: 1.0e-6            # Discriminator's epsilon.
        weight_decay: 0.0      # Discriminator's weight decay coefficient.
    discriminator_scheduler_params:
        step_size: 200000      # Discriminator's scheduler step size.
        gamma: 0.5             # Discriminator's scheduler gamma.
                            # At each step size, lr will be multiplied by this parameter.


###########################################################
#             STRATEGY SETTING               #
###########################################################
strategy_name: "PWGStrategy"
strategy_params:
    lambda_adv: 4.0
    discriminator_start_steps: 100000
    generator_grad_norm: 10    # Generator's gradient norm.
    discriminator_grad_norm: 1 # Discriminator's gradient norm.


###########################################################
#             TRANINING SETTING               #
###########################################################
dataset_classname: "PWGAudioMelNoiseDataset" 
dataset_num_workers: 5
batch_mel_length: 48
train_batch_size: 8
max_train_steps: 400000 
log_interval_steps: 100


###########################################################
#             EVALUATE & TEST                #
###########################################################
eval_interval_steps: 1000


